### ISSUE TITLE
Rebuild Authorizations

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#411] opened 2015-09-20 19:22 UTC
Refactor into a proper permission system to better manage user permissions.

**Comment by markottaviani** [comment] 2015-09-20 19:22
https://github.com/elabs/pundit
https://github.com/CanCanCommunity/cancancan

**Comment by TheDudeWithTheThing** [comment] 2016-07-14 01:47
nice, thredded just moved to pundit so wanted an excuse to play with it

**Comment by markottaviani** [comment] 2016-07-15 23:55
Cool, let me know before you dive into this one.  It's probably worth talking to the Business and figuring out what the proper business roles are these days.

**Comment by TheDudeWithTheThing** [comment] 2016-08-04 02:32
#446 is a duplicate of this no?

**Comment by markottaviani** [comment] 2016-08-04 03:31
Nope, updated the description.  This is Authorization, the other is Authentication.

**Comment by markottaviani** [comment] 2017-11-21 00:24
Stuff to check out: 

rolify and cancancan — Rolify allows the application to assign roles such as User or Admin on a User object. Then CanCanCan allows you to take those roles and apply authorization policies.

**Closed** 2024-05-18 15:41 UTC
Labels: Technical
